

### create role
POST http://localhost:3000/role/createRole
Content-Type: application/json

{
    "name": "test",
    "permissions": []
}

### view all roles
GET  http://localhost:3000/role/viewAllRoles


### view role
GET  http://localhost:3000/role/viewRole/64ae16e4dad9d8757cc2c833

### edit role
PUT  http://localhost:3000/role/editRole/64ae16e4dad9d8757cc2c833
Content-Type: application/json

{
    "name": "test updated",
    "permissions": []
}

### delete role
DELETE http://localhost:3000/role/deleteRole/64ae16e4dad9d8757cc2c833









